appName: checkout-api
appType: app
cluster: kind-prod
envName: prod
rollout:
  image:
    repository: ghcr.io/jfillman/checkout-api
    tag: 0.1.6-34db638
  ports:
    - name: http
      containerPort: 3000
