appName: checkout-api
appType: app
cluster: kind-prod
envName: prod
rollout:
  image:
    repository: ghcr.io/jfillman/checkout-api
    tag: 0.1.18-add7b73
  ports:
    - name: http
      containerPort: 3000
configMaps:
  - name: app-settings
    existingConfigMap: checkout-api-app-config
    mountPath: /config/app-settings
notifications:
  slack:
    enabled: true
    channel: "#all-idp-lab"
secrets:
  - name: dummy-secret-01
    as: env
    key: DUMMY_SECRET_01
  - name: dummy-secret-02
    as: volume
    mountPath: /etc/dummy-secret-02
  - name: dummy-secret-03
    as: env
    key: DUMMY_SECRET_03
    shared: true
releaseTracking:
  relayUrl: http://10.89.0.2:30880/outcome/kind-prod
  appNamespace: app-checkout-api-cicd
  gitUrl: https://github.com/jfillman/checkout-api
  gitRevision: 5002c33a33c1d15f52c6879694969774017ffd1e
  flowStartTime: "2026-08-23T00:12:34.081106014Z"
  chainId: a616defd-6c4f-4c1a-947b-7129adc1d5c6
  prUrl: https://github.com/jfillman/gitops-checkout-api/pull/13
  prCreatedAt: "2026-08-23T00:21:16.207746239Z"
  configJsonB64: ewogICJhcGlWZXJzaW9uIjogInBsYXRmb3JtL3YxIiwKICAia2luZCI6ICJQaXBlbGluZUNvbmZpZyIsCiAgImJ1aWxkIjogewogICAgImFnZW50IjogIm5vZGVqcy0yMCIsCiAgICAic2NyaXB0IjogIi4vYnVpbGQuc2giLAogICAgImRvY2tlcmZpbGUiOiAiLi9Eb2NrZXJmaWxlIiwKICAgICJ1bml0VGVzdCI6IHsKICAgICAgImVuYWJsZWQiOiB0cnVlLAogICAgICAiY29tbWFuZCI6ICIuL3Rlc3Quc2giCiAgICB9LAogICAgInNvbmFyIjogZmFsc2UsCiAgICAiY2FjaGUiOiB7CiAgICAgICJlbmFibGVkIjogdHJ1ZQogICAgfQogIH0sCiAgInRlc3QiOiB7CiAgICAic3VpdGUiOiAiaW50ZWdyYXRpb24iCiAgfSwKICAiZGVwbG95IjogewogICAgImxvd2VyRW52aXJvbm1lbnRzIjogWwogICAgICAiZGV2IgogICAgXSwKICAgICJ1cHBlckVudmlyb25tZW50cyI6IFsKICAgICAgewogICAgICAgICJuYW1lIjogInByb2QiLAogICAgICAgICJjbHVzdGVyIjogImtpbmQtcHJvZCIKICAgICAgfQogICAgXSwKICAgICJzdHJhdGVneSI6ICJkZXBsb3ltZW50IgogIH0sCiAgImVwaGVtZXJhbEVudmlyb25tZW50cyI6IHsKICAgICJicmFuY2giOiB7CiAgICAgICJlbmFibGVkIjogZmFsc2UKICAgIH0sCiAgICAicHVsbFJlcXVlc3QiOiB7CiAgICAgICJlbmFibGVkIjogdHJ1ZQogICAgfSwKICAgICJ0dGwiOiAiNWQiCiAgfSwKICAiZ292ZXJuYW5jZSI6IHsKICAgICJzYXN0IjogdHJ1ZSwKICAgICJpbWFnZVNjYW4iOiB0cnVlLAogICAgInBvbGljeUNoZWNrIjogdHJ1ZSwKICAgICJzYm9tIjogdHJ1ZSwKICAgICJhbGxvd2VkQ29tbWl0U2lnbmVycyI6IFsKICAgICAgImNyb3NzZmFkZXJAZ21haWwuY29tIiwKICAgICAgIjcyNjgzMzcramZpbGxtYW5AdXNlcnMubm9yZXBseS5naXRodWIuY29tIgogICAgXQogIH0sCiAgInNlY3JldHMiOiBbCiAgICB7CiAgICAgICJuYW1lIjogInNsYWNrLXdlYmhvb2stdXJsIgogICAgfQogIF0sCiAgIm5vdGlmaWNhdGlvbnMiOiB7CiAgICAic2xhY2siOiB7CiAgICAgICJlbmFibGVkIjogdHJ1ZSwKICAgICAgImNoYW5uZWwiOiAiI2FsbC1pZHAtbGFiIgogICAgfQogIH0sCiAgInBpcGVsaW5lcyI6IHsKICAgICJjaSI6IHsKICAgICAgInRyaWdnZXIiOiB7CiAgICAgICAgInNvdXJjZSI6ICJnaXQiLAogICAgICAgICJldmVudCI6ICJwdXNoIiwKICAgICAgICAiYnJhbmNoIjogIm1haW4iCiAgICAgIH0sCiAgICAgICJzdGVwcyI6IFsKICAgICAgICB7CiAgICAgICAgICAic3RhZ2UiOiAiYnVpbGQiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAic3RhZ2UiOiAidGVzdCIsCiAgICAgICAgICAiZW52IjogImRldiIKICAgICAgICB9LAogICAgICAgIHsKICAgICAgICAgICJzdGFnZSI6ICJkZXBsb3kiLAogICAgICAgICAgImVudiI6ICJkZXYiCiAgICAgICAgfSwKICAgICAgICB7CiAgICAgICAgICAic3RhZ2UiOiAicmVsZWFzZSIsCiAgICAgICAgICAiZW52IjogInByb2QiCiAgICAgICAgfQogICAgICBdCiAgICB9CiAgfQp9Cg==
